spring:
  datasource:
    username: root
    password: qwert12345
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cms?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update